name: Publish Nightly Builds
on:
  workflow_run:
    workflows:
      - Nightly Builds
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2.26.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        run_id: ${{ github.event.workflow_run.id }}
        skip_unpack: true
        path: ./artifacts

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Builds
        prerelease: false
        draft: false
        files: ./artifacts/*
        body: |
          This is an automatic nightly release of Psike Engine
          if you encounter any bugs in this release, please make an issue in the repo, it will be much appreciated, thank you!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}